name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t my_chess_engine .

    # tail -f /dev/null is used to keep the container running
    - name: Run Container
      run: docker run --name chess_engine_instance -d my_chess_engine tail -f /dev/null

    - name: Execute Tests
      run: docker exec chess_engine_instance /usr/src/app/ChessEngineTests
    
    - name: Execute Valgrind test
      run: docker exec chess_engine_instance /usr/src/app/valgrind_test

    - name: Cleanup
      run: docker rm -f chess_engine_instance

